const express=require('express');const http=require('http');const{WebSocketServer}=require('ws');const{Pool}=require('pg');const bcrypt=require('bcrypt');const jwt=require('jsonwebtoken');const cors=require('cors');
const app=express();const server=http.createServer(app);const wss=new WebSocketServer({server});
const PORT=process.env.PORT||3001;const JWT_SECRET=process.env.JWT_SECRET||'muda_segredo';const MT5_API_KEY=process.env.MT5_API_KEY||'muda_chave';const DATABASE_URL=process.env.DATABASE_URL;
const db=new Pool({connectionString:DATABASE_URL,ssl:{rejectUnauthorized:false}});
app.use(cors());app.use(express.json());
async function setupDatabase(){await db.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,email VARCHAR(255) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,name VARCHAR(100) DEFAULT 'Trader',plan VARCHAR(20) DEFAULT 'free',plan_expires TIMESTAMP,country VARCHAR(100) DEFAULT 'Moçambique',created_at TIMESTAMP DEFAULT NOW());CREATE TABLE IF NOT EXISTS signals(id SERIAL PRIMARY KEY,symbol VARCHAR(20) NOT NULL,signal VARCHAR(10) NOT NULL,entry DECIMAL(15,5),tp DECIMAL(15,5),sl DECIMAL(15,5),timeframe VARCHAR(5),confidence INTEGER,risk VARCHAR(20),object_id VARCHAR(255),source VARCHAR(50) DEFAULT 'MT5_BRIDGE',created_at TIMESTAMP DEFAULT NOW());CREATE TABLE IF NOT EXISTS payments(id SERIAL PRIMARY KEY,user_id INTEGER REFERENCES users(id),method VARCHAR(20),amount DECIMAL(10,2),plan VARCHAR(20),status VARCHAR(20) DEFAULT 'pending',reference VARCHAR(100),created_at TIMESTAMP DEFAULT NOW());`);console.log('✅ Base de dados pronta');}
const wsClients=new Map();
wss.on('connection',(ws)=>{ws.on('message',async(raw)=>{try{const msg=JSON.parse(raw);if(msg.type==='auth'){const decoded=jwt.verify(msg.token,JWT_SECRET);const result=await db.query('SELECT id,plan,plan_expires FROM users WHERE id=$1',[decoded.id]);const user=result.rows[0];if(!user){ws.send(JSON.stringify({type:'auth_error',msg:'Não encontrado'}));return;}const planActive=user.plan==='pro'&&(!user.plan_expires||new Date(user.plan_expires)>new Date());wsClients.set(ws,{userId:user.id,plan:planActive?'pro':'free'});ws.send(JSON.stringify({type:'auth_ok',plan:planActive?'pro':'free'}));if(planActive){const recent=await db.query('SELECT * FROM signals ORDER BY created_at DESC LIMIT 10');ws.send(JSON.stringify({type:'signals_history',signals:recent.rows}));}}}catch(err){ws.send(JSON.stringify({type:'error',msg:'Token inválido'}));}});ws.on('close',()=>wsClients.delete(ws));ws.on('error',()=>wsClients.delete(ws));});
function broadcastSignalToPro(signal){const payload=JSON.stringify({type:'new_signal',signal});wsClients.forEach((meta,ws)=>{if(meta.plan==='pro'&&ws.readyState===1)ws.send(payload);});}
app.get('/',(req,res)=>res.json({status:'ok',app:'Traders Arena API',version:'1.0'}));
app.post('/api/auth/register',async(req,res)=>{const{email,password,name}=req.body;if(!email||!password)return res.status(400).json({error:'Email e password obrigatórios'});try{const hash=await bcrypt.hash(password,12);const result=await db.query('INSERT INTO users(email,password_hash,name)VALUES($1,$2,$3)RETURNING id,email,name,plan',[email.toLowerCase(),hash,name||'Trader']);const user=result.rows[0];const token=jwt.sign({id:user.id,plan:user.plan},JWT_SECRET,{expiresIn:'30d'});res.status(201).json({token,user});}catch(err){if(err.code==='23505')return res.status(409).json({error:'Email já registado'});res.status(500).json({error:'Erro interno'});}});
app.post('/api/auth/login',async(req,res)=>{const{email,password}=req.body;if(!email||!password)return res.status(400).json({error:'Email e password obrigatórios'});try{const result=await db.query('SELECT * FROM users WHERE email=$1',[email.toLowerCase()]);const user=result.rows[0];if(!user)return res.status(401).json({error:'Credenciais inválidas'});const valid=await bcrypt.compare(password,user.password_hash);if(!valid)return res.status(401).json({error:'Credenciais inválidas'});const token=jwt.sign({id:user.id,plan:user.plan},JWT_SECRET,{expiresIn:'30d'});res.json({token,user:{id:user.id,email:user.email,name:user.name,plan:user.plan,plan_expires:user.plan_expires}});}catch(err){res.status(500).json({error:'Erro interno'});}});
function requireAuth(req,res,next){const auth=req.headers.authorization;if(!auth||!auth.startsWith('Bearer '))return res.status(401).json({error:'Token necessário'});try{req.user=jwt.verify(auth.split(' ')[1],JWT_SECRET);next();}catch{res.status(401).json({error:'Token inválido ou expirado'});}}
async function requirePro(req,res,next){try{const result=await db.query('SELECT plan,plan_expires FROM users WHERE id=$1',[req.user.id]);const user=result.rows[0];if(!user)return res.status(404).json({error:'Não encontrado'});const planActive=user.plan==='pro'&&(!user.plan_expires||new Date(user.plan_expires)>new Date());if(!planActive)return res.status(403).json({error:'Acesso exclusivo para assinantes Pro'});next();}catch{res.status(500).json({error:'Erro interno'});}}
function requireMT5Key(req,res,next){const key=req.headers['x-api-key'];if(!key||key!==MT5_API_KEY)return res.status(403).json({error:'API Key inválida'});next();}
app.post('/api/signals',requireMT5Key,async(req,res)=>{const{symbol,signal,entry,tp,sl,timeframe,confidence,risk,object_id}=req.body;if(!symbol||!signal)return res.status(400).json({error:'symbol e signal obrigatórios'});if(object_id){const dup=await db.query(`SELECT id FROM signals WHERE object_id=$1 AND created_at>NOW()-INTERVAL '5 minutes'`,[object_id]);if(dup.rows.length>0)return res.status(200).json({status:'duplicate'});}try{const result=await db.query(`INSERT INTO signals(symbol,signal,entry,tp,sl,timeframe,confidence,risk,object_id,source)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)RETURNING *`,[symbol,signal,entry||0,tp||0,sl||0,timeframe||'?',confidence||80,risk||'Médio',object_id||null,'MT5_BRIDGE']);const saved=result.rows[0];broadcastSignalToPro(saved);res.status(201).json({status:'ok',signal:saved});}catch(err){res.status(500).json({error:'Erro ao guardar sinal'});}});
app.get('/api/signals',requireAuth,requirePro,async(req,res)=>{try{const result=await db.query('SELECT * FROM signals ORDER BY created_at DESC LIMIT 50');res.json({signals:result.rows});}catch(err){res.status(500).json({error:'Erro ao buscar sinais'});}});
app.post('/api/payments/confirm',requireAuth,async(req,res)=>{const{method,plan,reference}=req.body;const userId=req.user.id;const expires=new Date();expires.setDate(expires.getDate()+30);try{await db.query('INSERT INTO payments(user_id,method,plan,status,reference)VALUES($1,$2,$3,$4,$5)',[userId,method,plan,'pending',reference]);await db.query('UPDATE users SET plan=$1,plan_expires=$2 WHERE id=$3',[plan,expires,userId]);res.json({status:'pending_verification',expires});}catch(err){res.status(500).json({error:'Erro ao registar pagamento'});}});
app.get('/api/me',requireAuth,async(req,res)=>{try{const result=await db.query('SELECT id,email,name,plan,plan_expires,country,created_at FROM users WHERE id=$1',[req.user.id]);if(!result.rows[0])return res.status(404).json({error:'Não encontrado'});res.json(result.rows[0]);}catch{res.status(500).json({error:'Erro interno'});}});
setupDatabase().then(()=>{server.listen(PORT,()=>{console.log(`🚀 Traders Arena API na porta ${PORT}`);console.log(`🔑 MT5 Key: ${MT5_API_KEY.substring(0,8)}...`);});}).catch(err=>{console.error('❌ Erro:',err.message);process.exit(1);});
