const express=require('express');const http=require('http');const{WebSocketServer}=require('ws');const{Pool}=require('pg');const bcrypt=require('bcrypt');const jwt=require('jsonwebtoken');const cors=require('cors');
const app=express();const server=http.createServer(app);const wss=new WebSocketServer({server});
const PORT=process.env.PORT||3001;const JWT_SECRET=process.env.JWT_SECRET||'secret';const MT5_API_KEY=process.env.MT5_API_KEY||'key';const DATABASE_URL=process.env.DATABASE_URL;
const db=new Pool({connectionString:DATABASE_URL,ssl:{rejectUnauthorized:false},connectionTimeoutMillis:10000,idleTimeoutMillis:30000,max:5});
app.use(cors());app.use(express.json());
app.get('/',(req,res)=>res.json({status:'ok',app:'Traders Arena API',version:'1.0'}));
app.get('/health',(req,res)=>res.json({status:'ok'}));
async function setupDatabase(){try{await db.query(`CREATE TABLE IF NOT EXISTS users(id SERIAL PRIMARY KEY,email VARCHAR(255) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,name VARCHAR(100) DEFAULT 'Trader',plan VARCHAR(20) DEFAULT 'free',plan_expires TIMESTAMP,country VARCHAR(100) DEFAULT 'Mocambique',created_at TIMESTAMP DEFAULT NOW())`);await db.query(`CREATE TABLE IF NOT EXISTS signals(id SERIAL PRIMARY KEY,symbol VARCHAR(20),signal VARCHAR(10),entry DECIMAL(15,5),tp DECIMAL(15,5),sl DECIMAL(15,5),timeframe VARCHAR(5),confidence INTEGER,risk VARCHAR(20),object_id VARCHAR(255),source VARCHAR(50) DEFAULT 'MT5',created_at TIMESTAMP DEFAULT NOW())`);await db.query(`CREATE TABLE IF NOT EXISTS payments(id SERIAL PRIMARY KEY,user_id INTEGER,method VARCHAR(20),amount DECIMAL(10,2),plan VARCHAR(20),status VARCHAR(20) DEFAULT 'pending',reference VARCHAR(100),created_at TIMESTAMP DEFAULT NOW())`);console.log('DB pronta');}catch(e){console.error('DB erro:',e.message);}}
const wsClients=new Map();
wss.on('connection',(ws)=>{ws.on('message',async(raw)=>{try{const msg=JSON.parse(raw);if(msg.type==='auth'){const decoded=jwt.verify(msg.token,JWT_SECRET);const r=await db.query('SELECT id,plan,plan_expires FROM users WHERE id=$1',[decoded.id]);const u=r.rows[0];if(!u)return;const ok=u.plan==='pro'&&(!u.plan_expires||new Date(u.plan_expires)>new Date());wsClients.set(ws,{userId:u.id,plan:ok?'pro':'free'});ws.send(JSON.stringify({type:'auth_ok',plan:ok?'pro':'free'}));if(ok){const rec=await db.query('SELECT * FROM signals ORDER BY created_at DESC LIMIT 10');ws.send(JSON.stringify({type:'signals_history',signals:rec.rows}));}}}catch(e){}});ws.on('close',()=>wsClients.delete(ws));ws.on('error',()=>wsClients.delete(ws));});
function broadcast(signal){const p=JSON.stringify({type:'new_signal',signal});wsClients.forEach((m,ws)=>{if(m.plan==='pro'&&ws.readyState===1)ws.send(p);});}
app.post('/api/auth/register',async(req,res)=>{const{email,password,name}=req.body;if(!email||!password)return res.status(400).json({error:'Email e password obrigatorios'});try{const hash=await bcrypt.hash(password,12);const r=await db.query('INSERT INTO users(email,password_hash,name)VALUES($1,$2,$3)RETURNING id,email,name,plan',[email.toLowerCase(),hash,name||'Trader']);const u=r.rows[0];const token=jwt.sign({id:u.id,plan:u.plan},JWT_SECRET,{expiresIn:'30d'});res.status(201).json({token,user:u});}catch(e){if(e.code==='23505')return res.status(409).json({error:'Email ja registado'});res.status(500).json({error:'Erro interno'});}});
app.post('/api/auth/login',async(req,res)=>{const{email,password}=req.body;if(!email||!password)return res.status(400).json({error:'Email e password obrigatorios'});try{const r=await db.query('SELECT * FROM users WHERE email=$1',[email.toLowerCase()]);const u=r.rows[0];if(!u)return res.status(401).json({error:'Credenciais invalidas'});const v=await bcrypt.compare(password,u.password_hash);if(!v)return res.status(401).json({error:'Credenciais invalidas'});const token=jwt.sign({id:u.id,plan:u.plan},JWT_SECRET,{expiresIn:'30d'});res.json({token,user:{id:u.id,email:u.email,name:u.name,plan:u.plan}});}catch(e){res.status(500).json({error:'Erro interno'});}});
function requireAuth(req,res,next){const auth=req.headers.authorization;if(!auth||!auth.startsWith('Bearer '))return res.status(401).json({error:'Token necessario'});try{req.user=jwt.verify(auth.split(' ')[1],JWT_SECRET);next();}catch{res.status(401).json({error:'Token invalido'});}}
function requireMT5Key(req,res,next){if(req.headers['x-api-key']!==MT5_API_KEY)return res.status(403).json({error:'Key invalida'});next();}
app.post('/api/signals',requireMT5Key,async(req,res)=>{const{symbol,signal,entry,tp,sl,timeframe,confidence,risk,object_id}=req.body;if(!symbol||!signal)return res.status(400).json({error:'Campos obrigatorios'});try{const r=await db.query(`INSERT INTO signals(symbol,signal,entry,tp,sl,timeframe,confidence,risk,object_id)VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9)RETURNING *`,[symbol,signal,entry||0,tp||0,sl||0,timeframe||'?',confidence||80,risk||'Medio',object_id||null]);broadcast(r.rows[0]);res.status(201).json({status:'ok',signal:r.rows[0]});}catch(e){res.status(500).json({error:'Erro'});}});
app.get('/api/signals',requireAuth,async(req,res)=>{try{const r=await db.query('SELECT * FROM signals ORDER BY created_at DESC LIMIT 50');res.json({signals:r.rows});}catch(e){res.status(500).json({error:'Erro'});}});
app.post('/api/payments/confirm',requireAuth,async(req,res)=>{const{method,plan,reference}=req.body;const expires=new Date();expires.setDate(expires.getDate()+30);try{await db.query('INSERT INTO payments(user_id,method,plan,status,reference)VALUES($1,$2,$3,$4,$5)',[req.user.id,method,plan,'pending',reference]);await db.query('UPDATE users SET plan=$1,plan_expires=$2 WHERE id=$3',[plan,expires,req.user.id]);res.json({status:'ok',expires});}catch(e){res.status(500).json({error:'Erro'});}});
app.get('/api/me',requireAuth,async(req,res)=>{try{const r=await db.query('SELECT id,email,name,plan,plan_expires,country,created_at FROM users WHERE id=$1',[req.user.id]);res.json(r.rows[0]||{});}catch{res.status(500).json({error:'Erro'});}});
server.listen(PORT,()=>{console.log(`Traders Arena API na porta ${PORT}`);setupDatabase();});
